package my.projects.recipebook.models.dto.subrecipe;

import lombok.Getter;
import lombok.Setter;
import my.projects.recipebook.models.dto.ingredient.IngredientQuantityDTO;
import my.projects.recipebook.models.dto.ingredient.IngredientQuantityPostDTO;

import java.util.Collection;
import java.util.List;

/**
 * Domain class (entity) to carry all information from SubRecipe class for post call.
 * Is used in Mapper class where it carries between layers.
 * Includes autogenerated getters and setters from lombok.
 */
@Getter
@Setter
public class SubRecipePostDTO {
        private String title;
        private String instructions;
        private List<IngredientQuantityPostDTO> ingredients;
    }
