package my.projects.recipebook.models.dto.recipe;

import lombok.Getter;
import lombok.Setter;
import java.util.List;

/**
 * Domain class (entity) to carry all information from Recipe class for post call.
 * Is used in Mapper class where it carries between layers.
 * Includes autogenerated getters and setters from lombok.
 */
@Getter
@Setter
public class RecipePostDTO {
    private String title;
    private String description;
    private Integer cooktime;
    private String image;
    private String cuisine;
    private String type;
    private Integer portion;
    private List<Integer> subRecipeIds;
}



