package my.projects.recipebook.models.dto.recipe;

import lombok.Getter;
import lombok.Setter;

/**
 * Domain class (entity) to carry some information from Recipe class.
 * Is used in lists.
 * Is used in Mapper class where it carries between layers
 * Includes autogenerated getters and setters from lombok
 */
@Getter
@Setter
public class RecipeListDTO {
    private int id;
    private String title;
    private String description;
}
