package my.projects.recipebook.models.dto.recipe;

import lombok.Getter;
import lombok.Setter;
import my.projects.recipebook.models.AppUser;
import my.projects.recipebook.models.Ingredient;
import my.projects.recipebook.models.SubRecipe;
import my.projects.recipebook.models.dto.appuser.AppUserDTO;
import my.projects.recipebook.models.dto.ingredient.IngredientDTO;
import my.projects.recipebook.models.dto.ingredient.IngredientQuantityDTO;

import java.time.LocalDate;
import java.util.Collection;
import java.util.Date;
import java.util.List;

/**
 * Domain class (entity) to carry all information from Recipe class.
 * Is used in Mapper class where it carries between layers.
 * Includes autogenerated getters and setters from lombok.
 */
@Getter
@Setter
public class RecipeDTO {
    private int id;
    private String title;
    private String description;
    private Integer cooktime;
    private String image;
    private String cuisine;
    private String type;
    private Integer portion;
    private List<SubRecipe> subRecipes;
    //private AppUserDTO appUser;
}
