package my.projects.recipebook.models.dto.appuser;

import lombok.Getter;
import lombok.Setter;

/**
 * Domain class (entity) to carry all information from User class for post call.
 * Is used in Mapper class where it carries between layers.
 * Includes autogenerated getters and setters from lombok.
 */
@Getter
@Setter
public class AppUserPostDTO {
    private String username;
    private String image;
    private String firstname;
    private String lastname;
}
