package my.projects.recipebook.models.dto.grocery;

import lombok.Getter;
import lombok.Setter;
import my.projects.recipebook.models.Ingredient;
import my.projects.recipebook.models.dto.ingredient.IngredientQuantityListDTO;

import java.util.Collection;

/**
 * Domain class (entity) to carry all information from Grocery class.
 * Is used in Mapper class where it carries between layers.
 * Includes autogenerated getters and setters from lombok.
 */
@Getter
@Setter
public class GroceryDTO {
    private int id;
    private Ingredient ingredient;
    private Collection<IngredientQuantityListDTO> quantities;
}
